#!/bin/bash 
  
cd
rm -rf CCMINER-SERVER
git clone https://github.com/saengx/CCMINER-SERVER
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/CCMINER-SERVER/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner backup restore up-grade
cd
cd CCMINER-SERVER
chmod +x setupdate.sh
sh setupdate.sh
